//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Security;
    public partial class Manager
    {
        public int ID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "First name is required")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Last name is required")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Age is required")]
        public string Age { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Gender is required")]
        public string Gender { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Contact Number is required")]
        [Display(Name = "Contact Number")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Invalid Mobile Number")]
        public string ContactNumber { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Manager Id is required")]
        [Display(Name = "Manager Id")]
        public int ManagerID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Password is required")]
        [MembershipPassword
            (
               MinRequiredNonAlphanumericCharacters = 1,
               MinNonAlphanumericCharactersError = "Password must contain atleast one symbol(!,@,#,$,&,*,etc).",
               ErrorMessage = "Password should contain 8 characters and one symbol(!,@,#,$,&,*,etc).",
               MinRequiredPasswordLength = 8
             )
         ]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}
